#pragma once

// This file is a TouchGFX integration template.
// Copy the methods and members into the View class generated by TouchGFX Designer,
// for example gui/include/gui/screen1_screen/Screen1View.hpp.

#include <gui_generated/screen1_screen/Screen1ViewBase.hpp>
#include <gui/screen1_screen/Screen1Presenter.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/widgets/TextAreaWithWildcard.hpp>
#include <touchgfx/Color.hpp>
#include <gui/common/Game2048Engine.hpp>
#include <gui/common/FlashStorage.hpp>

class Screen1View : public Screen1ViewBase {
public:
    Screen1View();
    virtual ~Screen1View() {}

    virtual void setupScreen();
    virtual void tearDownScreen();
    virtual void handleClickEvent(const ClickEvent& event);
    virtual void handleDragEvent(const DragEvent& event);
    virtual void handleTickEvent();

private:
    static constexpr uint8_t MaxBoard = game2048::MaxBoard;
    static constexpr int BoardLeft = 8;
    static constexpr int BoardTop = 82;
    static constexpr int BoardPixels = 208;
    static constexpr int Gap = 4;
    static constexpr uint8_t ButtonCount = 13;

    game2048::Engine game_;
    appstorage::SaveData saveData_;
    uint32_t highScore_[game2048::MaxBoard + 1] = {};
    uint8_t theme_ = 0;
    bool paused_ = false;
    bool menuVisible_ = false;
    bool dragActive_ = false;
    int16_t dragStartX_ = 0;
    int16_t dragStartY_ = 0;
    uint32_t tickCounter_ = 0;
    uint8_t feedbackTicks_ = 0;

    bool animActive_ = false;
    uint8_t animTick_ = 0;
    static constexpr uint8_t animMaxTicks_ = 6;
    uint8_t animType_[MaxBoard][MaxBoard] = {};

    touchgfx::Box background_;
    touchgfx::Box headerBackground_;
    touchgfx::Box boardBackground_;
    touchgfx::Box statusBackground_;
    touchgfx::Box tiles_[MaxBoard][MaxBoard];
    touchgfx::Box buttonBoxes_[ButtonCount];
    touchgfx::TextAreaWithOneWildcard tileText_[MaxBoard][MaxBoard];
    touchgfx::TextAreaWithOneWildcard titleText_;
    touchgfx::TextAreaWithOneWildcard scoreText_;
    touchgfx::TextAreaWithOneWildcard bestText_;
    touchgfx::TextAreaWithOneWildcard statusText_;
    touchgfx::TextAreaWithOneWildcard buttonText_[ButtonCount];

    Unicode::UnicodeChar tileBuffers_[MaxBoard][MaxBoard][8];
    Unicode::UnicodeChar titleBuffer_[16];
    Unicode::UnicodeChar scoreBuffer_[24];
    Unicode::UnicodeChar bestBuffer_[24];
    Unicode::UnicodeChar statusBuffer_[32];
    Unicode::UnicodeChar buttonBuffers_[ButtonCount][12];
    Unicode::UnicodeChar feedbackBuffer_[32];

    void drawAll();
    void drawHeader();
    void drawBoard();
    void drawButtons();
    void drawStatus();
    void applyMove(game2048::Direction direction);
    void onTap(int16_t x, int16_t y);
    void restartCurrentBoard();
    void changeBoard(int delta);
    void cycleTheme();
    void saveGame();
    void loadGame();
    bool persist(bool includeSnapshot);
    void setFeedback(const char* text, uint8_t ticks = 45);
    void configureButton(uint8_t index, int16_t x, int16_t y, int16_t w, int16_t h, const char* label, bool visible);
    uint16_t bgColor() const;
    uint16_t panelColor() const;
    uint16_t tileColor(uint16_t value) const;
    uint16_t buttonColor() const;
    bool hit(int16_t x, int16_t y, int16_t bx, int16_t by, int16_t bw, int16_t bh) const;
};
