// This file is a TouchGFX integration template.
// It assumes a 240x320 display and the default screen generated by TouchGFX is Screen1.
// If your generated screen has another name, rename Screen1View/Screen1ViewBase includes accordingly.

#include <gui/screen1_screen/Screen1View.hpp>
#include <touchgfx/Unicode.hpp>
#include "stm32f4xx_hal.h"
#include "Game2048Engine.hpp"

Screen1View::Screen1View() {
}

void Screen1View::setupScreen() {
    Screen1ViewBase::setupScreen();

    game_.begin(HAL_GetTick(), game2048::DefaultBoard);

    background_.setPosition(0, 0, 240, 320);
    boardBackground_.setPosition(BoardLeft, BoardTop, BoardPixels, BoardPixels);
    add(background_);
    add(boardBackground_);

    titleText_.setPosition(8, 8, 110, 24);
    scoreText_.setPosition(8, 32, 140, 20);
    bestText_.setPosition(8, 52, 140, 20);
    statusText_.setPosition(20, 136, 200, 48);
    add(titleText_);
    add(scoreText_);
    add(bestText_);
    add(statusText_);

    for (uint8_t r = 0; r < MaxBoard; r++) {
        for (uint8_t c = 0; c < MaxBoard; c++) {
            add(tiles_[r][c]);
            tileText_[r][c].setWildcard(tileBuffers_[r][c]);
            tileText_[r][c].setTypedText(TypedText(T_SINGLEUSEID1));
            add(tileText_[r][c]);
        }
    }

    titleText_.setTypedText(TypedText(T_SINGLEUSEID1));
    scoreText_.setWildcard(scoreBuffer_);
    scoreText_.setTypedText(TypedText(T_SINGLEUSEID1));
    bestText_.setWildcard(bestBuffer_);
    bestText_.setTypedText(TypedText(T_SINGLEUSEID1));
    statusText_.setWildcard(statusBuffer_);
    statusText_.setTypedText(TypedText(T_SINGLEUSEID1));

    drawAll();
}

void Screen1View::tearDownScreen() {
    Screen1ViewBase::tearDownScreen();
}

void Screen1View::handleClickEvent(const ClickEvent& event) {
    Screen1ViewBase::handleClickEvent(event);

    if (event.getType() == ClickEvent::PRESSED) {
        dragActive_ = true;
        dragStartX_ = event.getX();
        dragStartY_ = event.getY();
        return;
    }

    if (event.getType() == ClickEvent::RELEASED) {
        int16_t dx = event.getX() - dragStartX_;
        int16_t dy = event.getY() - dragStartY_;
        dragActive_ = false;

        if (abs(dx) > 45 || abs(dy) > 45) {
            if (abs(dx) > abs(dy)) {
                applyMove(dx > 0 ? game2048::Direction::Right : game2048::Direction::Left);
            } else {
                applyMove(dy > 0 ? game2048::Direction::Down : game2048::Direction::Up);
            }
        } else {
            onTap(event.getX(), event.getY());
        }
    }
}

void Screen1View::handleDragEvent(const DragEvent& event) {
    Screen1ViewBase::handleDragEvent(event);
}

void Screen1View::handleTickEvent() {
    Screen1ViewBase::handleTickEvent();
    tickCounter_++;
}

void Screen1View::drawAll() {
    background_.setColor(bgColor());
    boardBackground_.setColor(panelColor());
    drawHeader();
    drawBoard();
    drawStatus();
    invalidate();
}

void Screen1View::drawHeader() {
    Unicode::snprintf(scoreBuffer_, 24, "Score %lu", game_.score());
    Unicode::snprintf(bestBuffer_, 24, "Best %lu", highScore_[game_.size()]);
}

void Screen1View::drawBoard() {
    int cellPx = (BoardPixels - Gap * (game_.size() + 1)) / game_.size();

    for (uint8_t r = 0; r < MaxBoard; r++) {
        for (uint8_t c = 0; c < MaxBoard; c++) {
            bool visible = r < game_.size() && c < game_.size();
            tiles_[r][c].setVisible(visible);
            tileText_[r][c].setVisible(visible);
            if (!visible) {
                continue;
            }

            int x = BoardLeft + Gap + c * (cellPx + Gap);
            int y = BoardTop + Gap + r * (cellPx + Gap);
            uint16_t value = game_.cell(r, c);
            tiles_[r][c].setPosition(x, y, cellPx, cellPx);
            tiles_[r][c].setColor(tileColor(value));

            tileText_[r][c].setPosition(x, y + cellPx / 2 - 10, cellPx, 24);
            if (value == 0) {
                Unicode::snprintf(tileBuffers_[r][c], 8, "");
            } else {
                Unicode::snprintf(tileBuffers_[r][c], 8, "%u", value);
            }
        }
    }
}

void Screen1View::drawStatus() {
    if (paused_) {
        Unicode::snprintf(statusBuffer_, 32, "PAUSED");
        statusText_.setVisible(true);
    } else if (game_.status() == game2048::Status::Won) {
        Unicode::snprintf(statusBuffer_, 32, "YOU WIN");
        statusText_.setVisible(true);
    } else if (game_.status() == game2048::Status::GameOver) {
        Unicode::snprintf(statusBuffer_, 32, "GAME OVER");
        statusText_.setVisible(true);
    } else {
        Unicode::snprintf(statusBuffer_, 32, "");
        statusText_.setVisible(false);
    }
}

void Screen1View::applyMove(game2048::Direction direction) {
    if (paused_ || menuVisible_) {
        return;
    }

    game2048::MoveResult result = game_.move(direction);
    if (result.moved && game_.score() > highScore_[game_.size()]) {
        highScore_[game_.size()] = game_.score();
    }
    drawAll();
}

void Screen1View::onTap(int16_t x, int16_t y) {
    if (hit(x, y, 150, 8, 82, 24)) {
        menuVisible_ = !menuVisible_;
    } else if (hit(x, y, 150, 38, 82, 24)) {
        paused_ = !paused_;
    } else if (hit(x, y, 8, 306, 50, 14)) {
        game_.undo();
    } else if (hit(x, y, 66, 306, 50, 14)) {
        restartCurrentBoard();
    } else if (hit(x, y, 124, 306, 50, 14)) {
        saveGame();
    } else if (hit(x, y, 182, 306, 50, 14)) {
        loadGame();
    }
    drawAll();
}

void Screen1View::restartCurrentBoard() {
    game_.restart(game_.size());
}

void Screen1View::changeBoard(int delta) {
    int next = static_cast<int>(game_.size()) + delta;
    if (next < game2048::MinBoard) next = game2048::MinBoard;
    if (next > game2048::MaxBoard) next = game2048::MaxBoard;
    game_.restart(static_cast<uint8_t>(next));
}

void Screen1View::cycleTheme() {
    theme_ = static_cast<uint8_t>((theme_ + 1) % 3);
}

void Screen1View::saveGame() {
    // In TouchGFX/CubeIDE, implement this with Flash storage or backup SRAM.
    // Keep it empty until the board-specific Flash write routine is added.
}

void Screen1View::loadGame() {
    // In TouchGFX/CubeIDE, implement this with Flash storage or backup SRAM.
}

uint16_t Screen1View::bgColor() const {
    if (theme_ == 1) return touchgfx::Color::getColorFromRGB(8, 42, 56);
    if (theme_ == 2) return touchgfx::Color::getColorFromRGB(0, 0, 0);
    return touchgfx::Color::getColorFromRGB(250, 248, 239);
}

uint16_t Screen1View::panelColor() const {
    if (theme_ == 1) return touchgfx::Color::getColorFromRGB(18, 92, 110);
    if (theme_ == 2) return touchgfx::Color::getColorFromRGB(34, 36, 54);
    return touchgfx::Color::getColorFromRGB(187, 173, 160);
}

uint16_t Screen1View::tileColor(uint16_t value) const {
    if (value == 0) {
        return touchgfx::Color::getColorFromRGB(205, 193, 180);
    }

    uint8_t level = 0;
    while (value > 2) {
        value >>= 1;
        level++;
    }
    if (level > 10) level = 10;

    static const uint8_t colors[11][3] = {
        {238, 228, 218}, {237, 224, 200}, {242, 177, 121}, {245, 149, 99},
        {246, 124, 95},  {246, 94, 59},   {237, 207, 114}, {237, 204, 97},
        {237, 200, 80},  {237, 197, 63},  {60, 58, 50}
    };
    return touchgfx::Color::getColorFromRGB(colors[level][0], colors[level][1], colors[level][2]);
}

bool Screen1View::hit(int16_t x, int16_t y, int16_t bx, int16_t by, int16_t bw, int16_t bh) const {
    return x >= bx && x < bx + bw && y >= by && y < by + bh;
}
